@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/64888fbcecf8671ce3701dea
//GET {{baseUrl}}/{{urlPath}}/post/comments/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/64888fbcecf8671ce3701dea
//GET {{baseUrl}}/{{urlPath}}/post/commentsnames/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/64888fbcecf8671ce3701dea/648b2e2f0e71fde16ffd7d12
//GET {{baseUrl}}/{{urlPath}}/post/single/comment/<postId>/<commentId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64721d3c668e5c9a396e5f70",
  "postId": "64888fbcecf8671ce3701dea",
  "comment": "second comment",
  "profilePicture": "https://res.cloudinary.com/dbwuwe27s/image/upload/v1685200189/64721d3c668e5c9a396e5f70"
}
