@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/64721d3c668e5c9a396e5f70
//GET {{baseUrl}}/{{urlPath}}/user/followers/<userId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/649ab45b86b1ab8faca3f3c9
//PUT {{baseUrl}}/{{urlPath}}/user/follow/<followeeId>
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/6489d842d587366768cb94f0/64721d3c668e5c9a396e5f70
//PUT {{baseUrl}}/{{urlPath}}/user/unfollow/<followeeId>/<followerId>
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/block/648ee957035cb959fd7165ab
//PUT {{baseUrl}}/{{urlPath}}/user/block/<followerId>
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/648ee957035cb959fd7165ab
//PUT {{baseUrl}}/{{urlPath}}/user/unblock/<followerId>
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
